version: 1.0.{build}

shallow_clone: true

matrix:
  fast_finish: true

environment:
  matrix:
    - GENERATOR: "Visual Studio 15"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15"
      CONFIG: Release

os: Visual Studio 2015

before_build:
    - cmd: dir "C:\Program Files (x86)\"
    - cmd: dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\"
    - cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"
  - cmake --build _builds --config "%CONFIG%" --target tests
