version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:stretch
    steps:
      - checkout
      - run: mkdir build
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: cd build && cmake ..
      - run: cd build && make
  test:
    docker:
      - image: circleci/ruby:stretch
    steps:
      - checkout
      - run: mkdir build
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: cd build && cmake ..
      - run: cd build && make check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
